twoscoops/flavor/urls.py
__author__ = 'plevytskyi'
from django.conf.urls import url
from flavor import views


urlpatterns = [
    url(regex=r"^$", view=views.FlavorCreateView.as_view(), name="flavor_create"),
    url(regex=r"^detail/(?P<slug>\w+)", view=views.FlavorDetailView.as_view(), name="detail")
    ]

twoscoops/sprinkles/urls.py
__author__ = 'plevytskyi'
from django.conf.urls import url
from sprinkles.views import sprinkle_list


urlpatterns = [
    url(regex=r"^$", view=sprinkle_list, name="sprinkle")
    ]

twoscoops/testings/urls.py
__author__ = 'plevytskyi'
from django.conf.urls import url
from . import views

urlpatterns = [
    url(regex=r"^$",
        view=views.TasteListView.as_view(),
        name="list"
        ),
    url(
        regex=r"^(?P<pk>\d+)/$",
        view=views.TasteDetailView.as_view(),
        name="detail"
        ),
    url(
        regex=r"^(?P<pk>\d+)/results/$",
        view=views.TasteResultsView.as_view(),
        name="results"
        ),
    url(
        regex=r"^(?P<pk>\d+)/update/$",
        view=views.TasteUpdateView.as_view(),
        name="update"
    ),
    url(regex=r"^mix/$", view=views.FruityFlavorView.as_view(), name="mix"),
]

twoscoops/twoscoops/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^testings/', include('testings.urls', namespace='tastings')),
    url(r'^flavors/', include('flavor.urls', namespace='flavors')),
    url(r'^sprinkles/', include('sprinkles.urls', namespace='tastings'))
]

twoscoops/core/models.py
__author__ = 'plevytskyi'
from django.db import models
from .validators import validate_tasty


class TastyTitleAbstractModel(models.Model):
    title = models.CharField(max_length=255, validators=[validate_tasty])

    class Meta:
        abstract = True

twoscoops/flavor/models.py
from django.core.urlresolvers import reverse
from django.db import models

from core.models import TastyTitleAbstractModel

STATUS = (
    (0, "zero"),
    (1, "one")
)


class Flavor(TastyTitleAbstractModel):

    slug = models.SlugField(unique=True)
    scoops_remaining = models.IntegerField(default=0, choices=STATUS)

    def get_absolute_url(self):
        return reverse("flavors:detail", kwargs={"slug": self.slug})

twoscoops/sprinkles/models.py
from django.db import models


class Sprinkle(models.Model):
    name = models.TextField(max_length=50)
    body = models.TextField(max_length=256)

twoscoops/testings/models.py
from django.db import models


class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides self-
    . fields.
    updating ``created`` and ``modified``
    """
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Tasting(TimeStampedModel):
    name = models.CharField(max_length=50)
    body = models.CharField(max_length=256)

twoscoops/flavor/views.py
from django.contrib import messages
from django.views.generic import CreateView, UpdateView, DetailView

from .models import Flavor


class FlavorActionMixin(object):
    fields = ('title', 'slug', 'scoops_remaining')

    @property
    def success_msg(self):
        return NotImplemented

    def form_valid(self, form):
        messages.info(self.request, self.success_msg)
        return super(FlavorActionMixin, self).form_valid(form)


class FlavorCreateView(FlavorActionMixin, CreateView):
    model = Flavor
    fields = ('title', 'slug', 'scoops_remaining')
    success_msg = "Flavor created!"


class FlavorUpdateView(FlavorActionMixin, UpdateView):
    model = Flavor
    fields = ('title', 'slug', 'scoops_remaining')
    success_msg = "Flavor updated!"


class FlavorDetailView(DetailView):
    model = Flavor

twoscoops/sprinkles/views.py
from django.shortcuts import render

from django.shortcuts import get_object_or_404
from django.shortcuts import render
from .models import Sprinkle
from.decorators import check_sprinkles


def sprinkle_list(request):
    """Standard list view"""

    return render(request,  "sprinkles/sprinkle_list.html", {"sprinkles": Sprinkle.objects.all()})


def sprinkle_detail(request, pk):
    """Standard detail view"""
    sprinkle = get_object_or_404(Sprinkle, pk=pk)

    return render(request, "sprinkles/sprinkle_detail.html", {"sprinkle": sprinkle})

twoscoops/testings/views.py
from django.views.generic import DetailView, ListView, TemplateView, UpdateView
from django.core.urlresolvers import reverse

from .models import Tasting


class FreshFruitMixin(object):
    def get_context_data(self, **kwargs):
        context = super(FreshFruitMixin, self).get_context_data(**kwargs)
        context["has_fresh_fruit"] = "Test"
        return context


class FruityFlavorView(FreshFruitMixin, TemplateView):
    template_name = "fruity_flavor.html"


class TasteListView(ListView):
    model = Tasting


class TasteDetailView(DetailView):
    model = Tasting


class TasteResultsView(TasteDetailView):
    template_name = "tastings/results.html"


class TasteUpdateView(UpdateView):
    model = Tasting
    fields = ('name', 'body')

    def get_success_url(self):
        return reverse("tastings:detail", kwargs={"pk": self.object.pk})

twoscoops/flavor/templates/flavor/flavor_detail.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block title %}Flavor Detail{% endblock title %}
{% block content %}
    <div class="col-md-12">
        {% bootstrap_messages %}
        {{ object.title }}
    </div>
{% endblock content %}

twoscoops/flavor/templates/flavor/flavor_form.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block title %}Creata Flavor{% endblock title %}
{% block content %}
    <div class="col-md-4 col-md-offset-4">
        <form action="" method="post" class="form">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% buttons %}
            <button type="submit" class="btn btn-primary">
              {% bootstrap_icon "star" %} Submit
            </button>
          {% endbuttons %}
        </form>
    </div>
{% endblock content %}

twoscoops/sprinkles/templates/sprinkles/sprinkle_list.html
{% extends "base.html" %}
{% block title %}Sprinkles{% endblock title %}
{% block content %}
<ul>
{% for object in sprinkles %}
    <li>
        {{ object.name }}
    </li>
{% endfor %}
</ul>
{% endblock content %}

twoscoops/templates/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    {% load staticfiles %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static "bootstrap/dist/css/bootstrap.min.css" %}"/>
    <script src="{% static "bootstrap/dist/js/bootstrap.min.js" %}"></script>
</head>
<body>
<div class="content">
    <h1 class="col-md-12">{% block title %}Some title{% endblock %}</h1>
    {% block content %}{% endblock %}
</div>
</body>
</html>

twoscoops/testings/templates/fruity_flavor.html
{% extends "../../twoscoops/../../templates/base.html" %}
{% block title %}Mix{% endblock title %}
{% block content %}
{{ has_fresh_fruit }}
{% endblock content %}

twoscoops/testings/templates/testings/tasting_detail.html
{% extends "base.html" %}
{% block title %}
    {{ block.super }}<br/>
    {{ object.name }}
{% endblock title %}
{% block content %}
good
{% endblock content %}

twoscoops/testings/templates/testings/tasting_form.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block title %}Update Tasting{% endblock title %}
{% block content %}
    <div class="col-md-4 col-md-offset-4">
        <form action="" method="post" class="form">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% buttons %}
            <button type="submit" class="btn btn-primary">
              {% bootstrap_icon "star" %} Submit
            </button>
          {% endbuttons %}
        </form>
    </div>
{% endblock content %}

twoscoops/testings/templates/testings/tasting_list.html
{% extends "base.html" %}
{% block title %}Tastings{% endblock title %}
{% block content %}
<ul>
{% for taste in tasting_list %}
<li>
    <a href="{% url "tastings:detail" taste.pk %}">{{ taste.name }}</a>
    <small>
        (<a href="{% url "tastings:update" taste.pk %}">update</a>)
    </small>
</li>
{% endfor %}
</ul>
{% endblock content %}